name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Build
      run: ./gradlew build
    - name: Install Heroku
      run: sudo snap install --classic heroku
    - name: Push to heroku
      run: git push heroku HEAD:master
