name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#    - name: Check Build
#      run: ./gradlew build
    - name: Install Heroku
      run: sudo snap install --classic heroku
    - name: Login to heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku login
    - name: Add heroku git remote
      run: heroku git:remote -a secure-scrubland-34237
    - name: Push to heroku
      run: git push heroku HEAD:master
