name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install heroko
      run: curl https://cli-assets.heroku.com/install.sh | sh
    - name: Check heroku version
      run: heroku --version
    - name: Login to heroku
      env:
        heroku_api_key: ${{ HEROKU_API_KEY }}
      run: heroku login
