name: CI/CD

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Build
      run: ./gradlew build
    - name: Push to Heroku
      run: sudo snap install --classic heroku & git push heroku master
